### ISSUE TITLE
`react-scripts start`

### ISSUE THREAD

**Issue by SJablonska** [Netflix/stethoscope#10]
npm ERR! stethoscope-react@0.1.0 start: `react-scripts start`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the stethoscope-react@0.1.0 start script.
npm ERR! This is most likely a problem with the stethoscope-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts start
npm ERR! You can get their info via:
npm ERR!     npm owner ls stethoscope-react
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.9.11-040911-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/gia-admin/stethoscope/stethoscope/ui
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/gia-admin/stethoscope/stethoscope/ui/npm-debug.log
npm ERR! not ok code 0
Makefile:49: recipe for target 'develop-ui' failed
make: *** [develop-ui] Error 1

**Comment by jkriss** [comment]
It looks like you're using a very old version of node (v0.10.29). We recommend at least node 6.4.

Here are the instructions for getting recent released installed on Debian: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
