### ISSUE TITLE
docker-compose up issue

### ISSUE THREAD

**Issue by scraxxy** [Netflix/stethoscope#11]
$ docker-compose up
ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.

$ cat docker-compose.yml 
version: '2'
services:
  login:
    extends:
      file: docker-compose.base.yml
      service: login
  api:
    extends:
      file: docker-compose.base.yml
      service: api
    links:
      - login
  nginx:
    extends:
      file: docker-compose.base.yml
      service: nginx
    links:
      - login
      - api
  node-builder:
    build:
      context: .
      dockerfile: Dockerfile-node
    volumes:
     - ./stethoscope/ui/src:/code/stethoscope/ui/src
     - ./stethoscope/static:/code/stethoscope/static
     - ./stethoscope/login:/code/stethoscope/login

I am not too familiar with the version function , any thoughts on how to resolve this?

**Comment by andrewmwhite** [comment]
This looks like the same issue as #6. If that solution doesn't work for you, please let us know.
