### ISSUE TITLE
setup.py egg_info

### ISSUE THREAD

**Issue by bwhua** [Netflix/stethoscope#120]
Hello,

I'm trying to run the backend of stethoscope and followed the instructions in Netflix/stethoscope/docs/backend.rst. I tried 'make develop' in a pyenv and got an error:

'''Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-546p715s/pymssql/
Makefile:13: recipe for target 'install-python-requirements' failed
make: *** [install-python-requirements] Error 1'''

**Comment by andrewmwhite** [comment]
I'm guessing this is the issue with pymssql described here:
https://stethoscope.readthedocs.io/en/latest/backend.html#errors-installing-pymssql

That's a pretty old workaround, though, there may be better ways now to get
pymssql installed and working with FreeTDS in the virtualenv.

**Comment by bwhua** [comment]
I ran those commands and still got the same error. I did get it to work by installing node js and running
sudo make develop.

**Comment by andrewmwhite** [comment]
That sounds like maybe you were using system python rather than the
virtualenv. You shouldn't need sudo.

**Comment by bwhua** [comment]
I'm not sure how to solve the issue, so I've tried re-doing everything in a fresh virtual machine. I now get this error:

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-O84oK5/Twisted/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-IR8AFt/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-O84oK5/Twisted/
Makefile:13: recipe for target 'install-python-requirements' failed
make: *** [install-python-requirements] Error 1

**Comment by andrewmwhite** [comment]
It's hard to tell what the actual problem is from that message. Is there a log file or any other information in `/tmp/pip-install-O84oK5/Twisted`.

**Comment by bwhua** [comment]
I can't find the directory pip-install 084ok5
