### ISSUE TITLE
OIDC with Google

### ISSUE THREAD

**Issue by vegardvaage** [Netflix/stethoscope#13]
I'm been trying to set up the OIDC login plugin with G Suite, and I believe I'm nearly there. 

I've been able to successfully get through the login and approval flow, and been redirected back to the Stethoscope app on the following URL:

http://stethoscope:5000/<21 digit numeric value>#

However, the GET request to that URL ends in a 400 Bad Request, with nothing additional in the Docker Compose logs. 

I do think I have the Google integration (with a service account) set up correctly, but it's hard to tell given the lack of feedback in the logs. 

My config looks like this:

```
OIDC_CALLBACK_URL = 'stethoscope'
OIDC_CLIENT_ID = '' //my client id
OIDC_CLIENT_SECRET = 'secret'
OIDC_AUTHORIZATION_URL = 'https://accounts.google.com/o/oauth2/v2/auth'
OIDC_CALLBACK_SCHEME = 'http'
OIDC_CALLBACK_PORT = 5000
OIDC_TOKEN_URL = 'https://accounts.google.com/o/oauth2/token'
OIDC_USERINFO_URL = 'https://www.googleapis.com/oauth2/v3/userinfo'

PLUGINS = {
  'google': {
    'GOOGLE_API_SECRETS': '''{
  "type": "service_account",
  "project_id": "stethoscope-redacted",
  "private_key_id": "redacted",
  "private_key": "redacted",
  "client_email": "redacted.iam.gserviceaccount.com",
  "client_id": "redacted",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/redacted.iam.gserviceaccount.com"
}''',


    'GOOGLE_API_USERNAME': 'Stethoscope',
    'GOOGLE_API_SCOPES': [
        "https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly",
        "https://www.googleapis.com/auth/admin.directory.device.mobile.readonly",
        "https://www.googleapis.com/auth/admin.directory.user.readonly",
        "https://www.googleapis.com/auth/admin.reports.audit.readonly",
        "https://www.googleapis.com/auth/admin.reports.usage.readonly",
    ]
  }
}
```

Any thoughts? :)

**Comment by elenoir** [comment]
Hello,

I think you should use the email account associated with your API developpers as the identifier in URL (such as someone%40gmail.com).

Also, the triple quote before GOOGLE_API_SECRETS seems weird since a blob JSON is expected.

If the team could provide concrete examples for each plugin, it would be really appreciated.

**Comment by elenoir** [comment]
Hello,

I think you should use the email account associated with your API developpers as the identifier in URL (such as someone%40gmail.com).

If the team could provide concrete examples for each plugin, it would be really appreciated.

In my case I have : 

PLUGINS = {
  'google': {
    'GOOGLE_API_SECRETS':
'''{
  "type": "service_account",
  "project_id": "stethoscope-160318",
  "private_key_id": "e267075d310ec2e1e60e3f8af6f186663b27ee75",
  "private_key": "-----BEGIN PRIVATE KEY-----BLABLABLA-----END PRIVATE KEY-----",
  "client_email": "713615339037-compute@developer.gserviceaccount.com",
  "client_id": "101104793176291395999",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/713615339037-compute%40developer.gserviceaccount.com"
}''',
    'GOOGLE_API_USERNAME': 'Stethoscope',
    'GOOGLE_API_SCOPES': [
    	"https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly",
    	"https://www.googleapis.com/auth/admin.directory.device.mobile.readonly",
    	"https://www.googleapis.com/auth/admin.directory.user.readonly",
    	"https://www.googleapis.com/auth/admin.reports.audit.readonly",
    	"https://www.googleapis.com/auth/admin.reports.usage.readonly"
  	]
  }
}

In the log I only see : 

api_1           | 2017-03-02T19:42:41+0000 [stderr#error] [Failure instance: Traceback: <type 'exceptions.RuntimeError'>: Unable to get credentials for Google API access: []
api_1           | 2017-03-02T19:42:41+0000 [stderr#error] /usr/local/lib/python2.7/threading.py:801:__bootstrap_inner
api_1           | 2017-03-02T19:42:41+0000 [stderr#error] /usr/local/lib/python2.7/threading.py:754:run
api_1           | 2017-03-02T19:42:41+0000 [stderr#error] /usr/local/lib/python2.7/site-packages/twisted/_threads/_threadworker.py:46:work
api_1           | 2017-03-02T19:42:41+0000 [stderr#error] /usr/local/lib/python2.7/site-packages/twisted/_threads/_team.py:190:doWork

Any thoughts?

**Comment by andrewmwhite** [comment]
Google appears to be sending the user back to the wrong local endpoint (not clear from our docs, but this should be `/auth/oidc`; Google is sending the user just to the root URI). I've replicated this behavior on my personal G Suite domain and am now trying to figure out why Google is not respecting the full redirect URI.

**Comment by andrewmwhite** [comment]
Please let me know if that commit doesn't fix your issue. Thanks for the bug report!

**Comment by vegardvaage** [comment]
That did indeed fix the login issue, thank you! Now I can start debugging why I'm not getting data from my Google service account... :) 

As @elenoir mentioned, config samples for each plugin would be greatly appreciated.

**Comment by andrewmwhite** [comment]
Glad that fixed your issue.

I'm working on the docs and will include config samples for each plugin.

**Comment by elenoir** [comment]
Hello,

The fix didn't fix my issue with my previous example.

I have another error now : 

2017-03-06T12:22:40+0000 [stderr#error] [Failure instance: Traceback: <type 'exceptions.RuntimeError'>: Unable to get credentials for Google API access: 'str' object has no attribute 'get'

**Comment by andrewmwhite** [comment]
@elenoir Your issue is different from @vegardvaage's -- theirs was with respect to using Google for authentication via OpenIDConnect. Yours is, I believe, in configuring the Google data source plugin.

You need to configure your `PLUGINS` dictionary like so:

```python
PLUGINS = {
  'google': {
    'GOOGLE_API_SECRETS': {
       "client_id": "<redacted>",
       "private_key": "-----BEGIN PRIVATE KEY-----<redacted>-----END PRIVATE KEY-----\n",
       "token_uri": "https://accounts.google.com/o/oauth2/token",
       "client_email": "<redacted>",
       "client_x509_cert_url": "<redacted>",
       "private_key_id": "<redacted>",
       "type": "service_account",
       "auth_uri": "https://accounts.google.com/o/oauth2/auth",
       "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
       "project_id": "<redacted>"
    },
    'GOOGLE_API_USERNAME': '<redacted>',
    'GOOGLE_API_SCOPES': [
      "https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly",
      "https://www.googleapis.com/auth/admin.directory.device.mobile.readonly",
      "https://www.googleapis.com/auth/admin.directory.user.readonly",
      "https://www.googleapis.com/auth/admin.reports.audit.readonly",
      "https://www.googleapis.com/auth/admin.reports.usage.readonly",
    ],
  }
}
```
