### ISSUE TITLE
cd stethoscope/ui && npm start fail

### ISSUE THREAD

**Issue by adotlad79** [Netflix/stethoscope#18]
cd stethoscope/ui && npm start

> stethoscope-react@0.1.0 start /home/ubuntu/stethoscope/stethoscope/ui
> react-scripts start

/usr/bin/env: ‘node’: No such file or directory

npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! stethoscope-react@0.1.0 start: `react-scripts start`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the stethoscope-react@0.1.0 start script 'react-scripts start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the stethoscope-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs stethoscope-react
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls stethoscope-react
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/stethoscope/stethoscope/ui/npm-debug.log
Makefile:49: recipe for target 'develop-ui' failed
make: *** [develop-ui] Error 1

**Comment by adotlad79** [comment]
Output of npm-debug.log

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle stethoscope-react@0.1.0~prestart: stethoscope-react@0.1.0
6 silly lifecycle stethoscope-react@0.1.0~prestart: no script for prestart, continuing
7 info lifecycle stethoscope-react@0.1.0~start: stethoscope-react@0.1.0
8 verbose lifecycle stethoscope-react@0.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle stethoscope-react@0.1.0~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/ubuntu/stethoscope/stethoscope/ui/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle stethoscope-react@0.1.0~start: CWD: /home/ubuntu/stethoscope/stethoscope/ui
11 silly lifecycle stethoscope-react@0.1.0~start: Args: [ '-c', 'react-scripts start' ]
12 info lifecycle stethoscope-react@0.1.0~start: Failed to exec start script
13 verbose stack Error: stethoscope-react@0.1.0 start: `react-scripts start`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:821:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid stethoscope-react@0.1.0
15 verbose cwd /home/ubuntu/stethoscope/stethoscope/ui
16 error Linux 4.4.0-64-generic
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
18 error node v4.2.6
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error stethoscope-react@0.1.0 start: `react-scripts start`
24 error spawn ENOENT
25 error Failed at the stethoscope-react@0.1.0 start script 'react-scripts start'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the stethoscope-react package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     react-scripts start
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs stethoscope-react
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls stethoscope-react
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
`

**Comment by jkriss** [comment]
Some Ubuntu versions have an older version of node installed as nodejs (vs. node). There's a description of why, as well as different ways to address it, here: https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-an-ubuntu-14-04-server

**Comment by andrewmwhite** [comment]
Closing as there's been no response from @adotlad79.
