### ISSUE TITLE
Using Google MDM plugin not displaying mobile device full detail

### ISSUE THREAD

**Issue by tchernsan** [Netflix/stethoscope#19]
I am using Google MDM plugin and do a test on my device to enable Google Device Policy. Stethoscope seem can detect my device but its showing unknown device and it couldn't show all the device information. 

Is there any specify configuration I need to configure at my Google Suite to enable Stethoscope to be able to retrieve data?

Thanks.

//CS

**Comment by andrewmwhite** [comment]
Is this an iOS device? See my comment in #20 for more information on Google's limitations.

**Comment by andrewmwhite** [comment]
Closing as there's been no response in over a week.
