### ISSUE TITLE
Is JAMF the only method to retrieve MacOS information?

### ISSUE THREAD

**Issue by tchernsan** [Netflix/stethoscope#20]
My organization OSes consist of MacOS, Windows, Linux and mobile devices. My understanding is through Google sync, (or Google MDM plugin) it could detect all my devices information, laptop or mobile as long as I login to my Google app. 

However I am struggling getting my MacOS information display on my device list. Could you clarify for Google MDM plugin, can I gather all OSes (for eg. Windows and MacOS) and mobile details (for eg, Android, IOS)  or I am only be able to retrieve mobile detail via Google MDM.

Thanks.

//CS

**Comment by andrewmwhite** [comment]
Google doesn't provide any information on MacOS or Windows devices. It provides full information for Android and ChromeOS devices and partial information for iOS devices.

**Comment by andrewmwhite** [comment]
To answer your question about JAMF: yes, currently JAMF is the only source Stethoscope supports for detailed information on MacOS devices.

**Comment by andrewmwhite** [comment]
Closing as there's been no response in over a week.
