### ISSUE TITLE
Duo Client failing

### ISSUE THREAD

**Issue by hatityechindove** [Netflix/stethoscope#26]
How can I go past this stage for the backend services when I run make deploy. I am using vagrant to do the test:
`
Downloading/unpacking duo-client==3.0 (from -r requirements.txt (line 8))
  Could not find any downloads that satisfy the requirement duo-client==3.0 (from -r requirements.txt (line 8))
No distributions at all found for duo-client==3.0 (from -r requirements.txt (line 8))
Storing complete log in /home/vagrant/.pip/pip.log
make: *** [install-python-requirements] Error 1
`

**Comment by andrewmwhite** [comment]
It's possible this is due to an issue connecting to PyPI. Are you getting this error consistently? 

If you would provide the contents of the log file (`/home/vagrant/.pip/pip.log`) mentioned in the error message, I might be able to help more.

**Comment by hatityechindove** [comment]
Thanks for the quick response. I took the footer:
`
Downloading/unpacking duo-client==3.0 (from -r requirements.txt (line 8))
  Getting page http://pypi.python.org/simple/duo-client
  URLs to search for versions for duo-client==3.0 (from -r requirements.txt (line 8)):
  * http://pypi.python.org/simple/duo-client/3.0
  * http://pypi.python.org/simple/duo-client/
  Getting page http://pypi.python.org/simple/duo-client/3.0
  Getting page http://pypi.python.org/simple/duo-client/
  Could not fetch URL http://pypi.python.org/simple/duo-client/3.0: HTTP Error 404: Not Found
  Will skip URL http://pypi.python.org/simple/duo-client/3.0 when looking for download links for duo-client==3.0 (from -r requirements.txt (line 8))
  Analyzing links from page https://pypi.python.org/simple/duo-client/
    Skipping link https://pypi.python.org/packages/2d/d4/a3e53834e21558624422fe8ca1cc3c188b9c91e7f5d516d1803c233b5661/duo_client-2.1-py2-none-any.whl#md5=ecf50a95ea33ffab73215be91fe2d80c (from https://pypi.python.org/simple/duo-client/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/ef/af/b58ff2872f165c98e5d0789b6840698237b9c70b11f45c46ad3a339abbaa/duo_client-3.0-py2.py3-none-any.whl#md5=25cb608553606af59f1f684660e097e2 (from https://pypi.python.org/simple/duo-client/); unknown archive format: .whl
  Could not find any downloads that satisfy the requirement duo-client==3.0 (from -r requirements.txt (line 8))
No distributions at all found for duo-client==3.0 (from -r requirements.txt (line 8))
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 223, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 948, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 152, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for duo-client==3.0 (from -r requirements.txt (line 8))
`

**Comment by andrewmwhite** [comment]
Looks like you may have an old version of `setuptools`. You can upgrade with `pip install --upgrade setuptools`, then re-run. Let me know if that fixes the problem.

**Comment by hatityechindove** [comment]
Didn't seem to fully work. I am now getting this error when I actually try and to do the upgrade:
`Downloading/unpacking setuptools>=0.7 (from distribute)
  Running setup.py egg_info for package setuptools
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "setuptools/__init__.py", line 10, in <module>
        from six.moves import filter, map
    ImportError: No module named six.moves
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 3, in <module>

  File "setuptools/__init__.py", line 10, in <module>

    from six.moves import filter, map

ImportError: No module named six.moves

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in /home/vagrant/.pip/pip.log`

The full log is:
`------------------------------------------------------------
/usr/bin/pip run on Tue Apr 18 23:05:40 2017
Downloading/unpacking distribute
  Running setup.py egg_info for package distribute
    running egg_info
    writing requirements to pip-egg-info/distribute.egg-info/requires.txt
    writing pip-egg-info/distribute.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/distribute.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/distribute.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info/distribute.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/distribute.egg-info/SOURCES.txt'
Downloading/unpacking setuptools>=0.7 (from distribute)
  Running setup.py egg_info for package setuptools
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "setuptools/__init__.py", line 10, in <module>
        from six.moves import filter, map
    ImportError: No module named six.moves
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 3, in <module>

  File "setuptools/__init__.py", line 10, in <module>

    from six.moves import filter, map

ImportError: No module named six.moves

----------------------------------------
Command python setup.py egg_info failed with error code 1
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 223, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 980, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 216, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 255, in call_subprocess
    % (command_desc, proc.returncode))a
InstallationError: Command python setup.py egg_info failed with error code 1
`
😢

**Comment by andrewmwhite** [comment]
It seems like you have some really old packages installed. I don't know much about Vagrant, but is it possible you could update your base image to something more recent? Debian Jessie or Ubuntu Xenial, perhaps? 

Otherwise, a `pip install --upgrade pip` might help.

**Comment by hatityechindove** [comment]
I upgraded the OS I was using on Vagrant and it worked. Thanks @andrewmwhite for the help
