### ISSUE TITLE
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by hatityechindove** [Netflix/stethoscope#27]
When I run make develop, using the instruction on the [backend setup](https://stethoscope.readthedocs.io/en/latest/backend.html) I am getting the below compilation error:
`reating build/temp.linux-x86_64-2.7/c

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o

c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory

 #include <ffi.h>

                 ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_vagrant/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-VxQZr4-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_vagrant/cffi
Storing debug log for failure in /tmp/tmp5Ael23
make: *** [install-python-requirements] Error 1`

Can I get a bit of assistance

**Comment by andrewmwhite** [comment]
Apologies for the late response. Looks like you're missing the headers for`libffi`. These can be installed via the `libffi-dev` package on Debian-based systems.

**Comment by hatityechindove** [comment]
I think I might be having a missing dependency:
`running build_ext

building '_cffi_backend' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/c

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o

x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/c/_cffi_backend.o -lffi -o build/lib.linux-x86_64-2.7/_cffi_backend.so

running install_lib

creating /usr/local/lib/python2.7/dist-packages/cffi

error: could not create '/usr/local/lib/python2.7/dist-packages/cffi': Permission denied

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_vagrant/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-tv3iKB-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_vagrant/cffi
Storing debug log for failure in /tmp/tmpR1TXEE
make: *** [install-python-requirements] Error 1`

**Comment by andrewmwhite** [comment]
Did you do a `sudo pip install` at some point? That may have messed up the permissions on some of those directories. I'm not too familiar with Vagrant so I'm reaching the end of my ability to give useful suggestions here.

**Comment by hatityechindove** [comment]
Thanks @andrewmwhite I am closing the ticket. I will find a way to resolve this

**Comment by andrewmwhite** [comment]
@hatityechindove I was able to get Stethoscope up and running on a `debian/jessie64` image via Vagrant using the commands here: 

https://gist.github.com/andrewmwhite/d495f498a751f3b1e7bf2cb0f9252514

Hope that helps.
