### ISSUE TITLE
Couldn't find service in docker

### ISSUE THREAD

**Issue by injcristianrojas** [Netflix/stethoscope#59]
Running `docker-compose up` I get the following message:

```fish
Cannot extend service 'base' in /home/tools/stethoscope/docker-compose.base.yml: Service not found
```

I'm using Docker Compose 1.15.0 over Docker 1.13.1 on Fedora 25.

**Comment by andrewmwhite** [comment]
Looks like this is a bug in docker-compose 1.15.0 that is fixed in 1.16.0-rc1:
https://github.com/docker/compose/issues/5122
https://github.com/docker/compose/issues/5067

If upgrading to 1.16.0-rc1 or later doesn't fix the issue for you, please feel free to re-open this issue.
