### ISSUE TITLE
Failing to run docker-compose up

### ISSUE THREAD

**Issue by adnanmig** [Netflix/stethoscope#6]
Hi guys,

just trying out the service and running into this issue:
![screen shot 2017-02-22 at 13 53 54](https://cloud.githubusercontent.com/assets/25726443/23227304/73041306-f906-11e6-8c4d-47fa4c64d3a3.png)
Is this something environment related on my end?

**Comment by jkriss** [comment]
@adnanmig: It sounds like you might have an older version of `docker-compose`. What's the output of `docker-compose --version`?

**Comment by adnanmig** [comment]
![screen shot 2017-02-22 at 16 18 52](https://cloud.githubusercontent.com/assets/25726443/23232807/a52698d6-f91a-11e6-927e-944ff37be40a.png)

**Comment by jkriss** [comment]
It looks like you'll need `docker-compose` version 1.10+ for version 2 config files to work: https://docs.docker.com/compose/compose-file/compose-versioning/

**Comment by adnanmig** [comment]
Thanks.
