### ISSUE TITLE
Problem setting up with docker-compose

### ISSUE THREAD

**Issue by fublu** [Netflix/stethoscope#67]
Hi,

This might be a dum newbe question, but i cans find any help on google.

When I run the command docker-compose up after cloning the repo I get this error:

ERROR: Cannot extend service 'base' in /stethoscope/docker-compose.base.yml: Service not found

I am using docker-compose version 1.15.0, build e12f3b9 on a ubuntu 16.04 server.

Does anyone have an idear to what the problem can be ?

**Comment by andrewmwhite** [comment]
Thanks for your interest in Stethoscope! 

I think this is the same as #59. Basically, you need to upgrade docker-compose. If that doesn't help you, feel free to re-open this issue.
