### ISSUE TITLE
Improve first-run experience

### ISSUE THREAD

**Issue by kevinburke** [Netflix/stethoscope#7]
I cloned the repository (ok) and got it running via `docker-compose up` and navigating to localhost:5000.

I expected to see something useful, but got nothing; the homepage tells me to review my devices, but I go to Devices and am told that I have no devices and no way to add them. Now am hunting around in config/api/production.py, various defaults.py for something to turn on.

Reading further I think I need to add a `PLUGINS = { }` dictionary to instance/config.py? But I have no idea what a successful value looks like.

I'm running on a Mac and it looks like JAMF is a security setting I could use? but I'm confused about that because the configuration seems to involve a hostname, which implies signing up for some service and sending my data to it, which I don't really want to do.

It would be nice if it were easier to get started and add devices, or if there were configuration examples that you could easily copy/paste from, or an easier pointer to the place you need to configure everything.

**Comment by andrewmwhite** [comment]
Thanks for your interest in using Stethoscope!

Unfortunately, I think Stethoscope is solving a different problem than what you have in mind. Stethoscope is designed to be deployed by an organization with an existing database of device information, e.g., JAMF, LANDESK, Google's MDM, etc. Stethoscope's primary purpose is to take device data from these sources and provide security advice regarding the configuration of those devices. It does not collect the information directly from individual devices.

**Comment by anujbhatt** [comment]
Thanks for the clarification @andrewmwhite.
