### ISSUE TITLE
setup.py egg_info

### ISSUE THREAD

**Issue by Garrett-Brown** [Netflix/stethoscope#73]
This is probably a fairly dumb problem but I am getting the following error when trying to run docker-compose up: 

> Command "python setup.py egg_info" failed with error code 1 in /code/
> make: *** [install-editable-package] Error 1
> Makefile:26: recipe for target 'install-editable-package' failed
> ERROR: Service 'login' failed to build: The command '/bin/sh -c make install-editable-package' returned a non-zero code: 2

Is there some package that I am missing or that is out of date?

**Comment by andrewmwhite** [comment]
I can't replicate this... are you using the master branch? If not, try that.

Otherwise, I can't tell why the command failed from those error messages. Could you post the full output?

**Comment by andrewmwhite** [comment]
Closing since there's been no response. Feel free to reopen if you think there's still an issue.
